### ISSUE TITLE
AlarmDao这个类你没有提交？？？？？？

### ISSUE THREAD

**Issue by zhuzhaolin** [ghbhaha/MyWeather#1]

**Comment by ghbhaha** [comment]
已提交

**Comment by zhr950224** [comment]
请问您用的是什么天气接口，我没有找到，是否收费？

**Comment by ghbhaha** [comment]
网上流传的小米的 flyme的：https://github.com/ghbhaha/-Api
或者这个我破解到的2345天气 https://github.com/ghbhaha/2345WeatherDecode
